version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/sourcecode
permissions:
   - object: /home/ubuntu/sourcecode
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/beforeInstallScript.sh
      runas: root
   AfterInstall:
    - location: scripts/afterInstallScript.sh
      runas: root 